
### Test lat,lon but you must add {{API_KEY}} to IntelliJ env
< {%
    request.variables.set("lat", `42.278046`)
    request.variables.set("lon", `-83.738220`)
%}
https://api.openweathermap.org/data/2.5/weather?lat={{lat}}&lon={{lon}}&appid={{API_KEY}}